version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
  service-balance:
    restart: unless-stopped
    image: nginx:1.12.0
    volumes:
      - ./service-balance/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '4050:80'
    # networks:
    #   - web-ui-network
    #   - worker-management-network

  final-project: # name of the first service
    build: 
      context: final-project
      dockerfile: Dockerfile
 
  api: # name of the second service
    build: 
      context: api
      dockerfile: Dockerfile
    # hostname: backend
    restart: on-failure
